import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Helloworld </h1>
        <Link href="about">About</Link>
        <Link href="uesr">uesr Database</Link>
        <Link href="docs">Document Database</Link>
        <Link href="docs/bclee">Bclee</Link>
        <Link href="docs/bclee/aaa">Bclee/aaa</Link>
      </main>
    </div>
  )
}
